# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'tutorialproject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tutorialproject
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  # target 'tutorialproject-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'tutorialprojectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'tutorialproject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tutorialproject-tvOS

  target 'tutorialproject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
